version: "3"

services:
          frontend:
              container_name: frontend
              build: /client/
              ports:
                - "8080:80"
              links:
                - "backend"
              networks:
                - frontend-net
          backend:
              container_name: backend
              build: /server/
              ports:
                - "3000:3000"
              networks:
                - backend-net
              environment:
                MONGODB_URL: mongodb://mongo:27017
              links:
                - "database"
          database:
              container_name: mongo
              image: mongo:latest
              networks:
                - mongo-net
              volumes:
                - ./data:data/db
              ports:
                - "27017:27017"

networks:
  frontend-net:
  backend-net:
  mongo-net: