version: "3"

services:
          frontend:
              container_name: frontend
              build: ./client
              ports:
                - "8080:80"
              networks:
                - app-net
              depends_on:
                - backend
          backend:
              container_name: backend
              build: ./server
              ports:
                - "3000:3000"
              networks:
                - app-net
              environment:
                MONGODB_URL: mongodb://mongo:27017
              depends_on:
                - database
          database:
              container_name: mongo
              image: mongo:latest
              networks:
                - app-net
              volumes:
                - data-volume:data/db
              ports:
                - "27017:27017"
              

networks:
  app-net:

volumes:
  data-volume: