version: "3"

networks:
  app-net:

services:
          frontend:
              container_name: frontend
              build: ./client
              ports:
                - "8080:80"
              networks:
                - app-net
          backend:
              container_name: backend
              build: ./server
              ports:
                - "3000:3000"
              networks:
                - app-net
              environment:
                MONGODB_URL: mongodb://mongo:27017
                PASSWORD_SECRET_KEY: V6I^Kzd9^8Y%Zq!&S2f47ctdwdx16Ljk
                TOKEN_SECRET_KEY: Y&z81D@b0gx%PnFA13iH9Zt5ZfkrLMjji
              depends_on:
                - database
          database:
              container_name: mongo
              image: mongo
              restart: always
              networks:
                - app-net
              ports:
                - "27017:27017"

